plugin: aws_ec2

#aws_access_key: AKIAZ6PYPA4GW4ESOP5S
#aws_secret_key: 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

regions:
  - ap-southeast-1
  - ap-south-1
  - us-west-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
